### ISSUE TITLE
Could the plugin extended?

### ISSUE THREAD

**Issue by plcdirect** [RickR2H/hikashop-free-product#2]
Nice plugin! Could the plugin also extended with a maximum price? and for example a country selection so that the item only is available for a certain country?

**Comment by RickR2H** [comment]
@plcdirect A maximum is not so logical because why want to add a product only when the total cart price is below a certain value? Do you have a use case?

Country can be added, but it will be a bit of work.

**Comment by RickR2H** [comment]
@plcdirect I did some investigation. Adding country will be difficult because the cart value is updated in the cart. So when a customer is not logged in, we cannot check what the country is from the customer. It will only work when they are logged in.

**Comment by plcdirect** [comment]
@RickR2H Hi Rick thanks for your quick reply. Actually i would use the plugin to add small order costs for a specific country. The small order cost will be an article and only be added if the order amount is between the 0 and 125 euro. I know it's not the original intent of this plugin but i hoped it could easily adjusted:-)

**Comment by RickR2H** [comment]
I think it's a better idea to make a special plugin for that. Or is it essential that the product is added? Are you willing to pay a small fee for the development?

**Comment by plcdirect** [comment]
Hello RickR2H, sorry for my late reply. We will think about it. but will also look at some standard solution for this. thanks for the answers.
