### ISSUE TITLE
Warning with PHP 7

### ISSUE THREAD

**Issue by plcdirect** [RickR2H/hikashop-free-product#3]
When activate the plugin i got this warning in Joomla:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemCustom_freeproduct has a deprecated constructor in /home/plcdirec/data/test/public_html/plugins/system/custom_freeproduct/custom_freeproduct.php on line 14

Is this something that can be fixed in a future version?

**Comment by MSnoeren** [comment]
The code has been improved and the constructor is removed. You should not get the warning anymore.

**Comment by plcdirect** [comment]
Thanks for the quick response will test it today!
